/*
 * Copyright (c) 2011-2020 HERE Global B.V. and its affiliate(s).
 * All rights reserved.
 * The use of this software is conditional upon having a separate agreement
 * with a HERE company for the use or utilization of this software. In the
 * absence of such agreement, the use of the software is not allowed.
 */

#import "NMAAdasisV2EngineDelegate.h"

@class NMAAdasisV2MessageConfiguration;

/**
 * Constant length of each binary encoded ADASIS v2 message.
 */
FOUNDATION_EXPORT NSUInteger const NMAAdasisV2MessageLength;

/**
 * The error domain for NMAAdasisV2Engine errors.
 */
FOUNDATION_EXPORT NSString *const _Nonnull kNMAAdasisV2EngineErrorDomain;


/**
 * `NMAAdasisV2Engine` uses electronic horizon to forecast a variety of ADAS compliant
 * road geometry and relevant map data to generate ADASIS v2 messages.
 */
@interface NMAAdasisV2Engine : NSObject

/**
 * Receiving the messages generated by ADASIS engine.
 *
 * See also `NMAAdasisV2EngineDelegate`
 */
@property (nonatomic, weak, nullable, readwrite) id<NMAAdasisV2EngineDelegate> delegate;

/**
 * Initializes a `NMAAdasisV2Engine` instance with the specified configuration.
 *
 * @param configuration Configuration which switches ON or OFF necessary ADASIS messages.
 */
- (nonnull instancetype)initWithConfiguration:(nonnull NMAAdasisV2MessageConfiguration *)configuration
NS_SWIFT_NAME(init(_:));

/**
 * Instances of this class should not be initialized. Call class methods only.
 */
- (nonnull instancetype)init NS_UNAVAILABLE;

/**
 * Instances of this class should not be initialized directly.
 */
+ (nonnull instancetype)new NS_UNAVAILABLE;

/**
 * Updates ADASIS engine with a new position. After calling update,
 * ADASIS version 2 protocol messages will be received via `NMAAdasisV2EngineDelegate`.
 *
 * @return error if the operation was not successful, otherwise nil.
 */
- (nullable NSError *)update;

@end
