/*
 * Copyright (c) 2011-2020 HERE Global B.V. and its affiliate(s).
 * All rights reserved.
 * The use of this software is conditional upon having a separate agreement
 * with a HERE company for the use or utilization of this software. In the
 * absence of such agreement, the use of the software is not allowed.
 */

#import <Foundation/Foundation.h>

#import "NMAPositionDataSource.h"

@class NMARoute;



/**
 *
 * A position data source which generates updates by simulating traversal of
 * a route.
 *
 * @note If background updates are enabled (see backgroundUpdatesEnabled from
 * NMAPositionDataSource) CLLocationManager is used to keep the app running in
 * the background but the positions generated come from route simulation traversal.
 */
@interface NMARoutePositionSource : NSObject<NMAPositionDataSource>

/**
 * Initialize an NMARoutePositionSource instance.
 */
- (nonnull instancetype)init NS_DESIGNATED_INITIALIZER;

/**
 * Initializes an NMARoutePositionSource with a given route.
 */
- (nonnull instancetype)initWithRoute:(nonnull NMARoute *)route;

/**
 * The route from which to generate position updates.
 *
 * @note The route can't be changed while position generation is active.
 */
@property (nonatomic, nullable) NMARoute *route;

/**
 * The time period between successive position updates, in seconds.
 *
 * @note The default value is 1.0s.
 */
@property (nonatomic) NSTimeInterval updateInterval;

/**
 * The simulated speed at which to traverse the route, in meters per second.
 *
 * @note The default value is 20m/s (72km/h)
 */
@property (nonatomic) float movementSpeed;

/**
 * The accuracy used in generated position updates, in meters.
 *
 * @note The default value is 5.0m.
 */
@property (nonatomic) float accuracy;

/**
 * Indicates whether or not the simulated positions are moving along the route.
 *
 * If stationary is YES, the currentPosition will remain fixed at the last calculated
 * position, or the beginning of the route if no progress has been made.
 *
 * @note The default value is NO.
 */
@property (nonatomic) BOOL stationary;

/**
 * Indicates whether the position source returns valid positions.
 *
 * Setting positionLost to YES can be used to simulate position loss. Position updates
 * will still be generated by the position source, but the currentPosition property
 * will always return nil.
 *
 * @note Progress along the route will continue regardless of the value of this property.
 *
 * @note The default value is NO.
 */
@property (nonatomic) BOOL positionLost;

/**
 * Erases all progress along the route.
 *
 * @note This method will not affect any properties, including the current route.
 */
- (void)reset;

@end
