/*
 * Copyright (c) 2011-2020 HERE Global B.V. and its affiliate(s).
 * All rights reserved.
 * The use of this software is conditional upon having a separate agreement
 * with a HERE company for the use or utilization of this software. In the
 * absence of such agreement, the use of the software is not allowed.
 */

@class NMAAdasisV2Engine;
@class NSData;



/**
 * An interface for responding to ADASIS v2 messages sent by the
 * NMAAdasisV2Engine.
 */
@protocol NMAAdasisV2EngineDelegate<NSObject>
@optional

/**
 * Called every time a new message is generated by ADASIS engine.
 *
 * @param adasisV2Engine The `NMAAdasisV2Engine` instance.
 * @param message Binary encoded ADASIS v2 message.
 * It contains `NMAAdasisV2MessageLength` bytes.
 */
- (void)adasisV2Engine:(nonnull NMAAdasisV2Engine *)adasisV2Engine
didReceiveAdasisMessage:(nonnull NSData *)message;

@end
