/*
 * Copyright (c) 2011-2020 HERE Global B.V. and its affiliate(s).
 * All rights reserved.
 * The use of this software is conditional upon having a separate agreement
 * with a HERE company for the use or utilization of this software. In the
 * absence of such agreement, the use of the software is not allowed.
 */

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>

#import "NMATypes.h"
#import "NMATrafficNotificationInfo.h"
#import "NMAMapGesture.h"
#import "NMAMapTileLayer.h"

@class NMAGeoBoundingBox;
@class NMAGeoCoordinates;
@class NMAMapObject;
@class NMAViewObject;
@class NMAMapOverlay;
@class NMAMapGesture;
@class NMAPositionIndicator;
@class NMAMapTransitLayer;
@class NMARoadElement;
@class NMARoute;
@class NMAVenue3dMapLayer;
@class NMAClusterLayer;
@class NMACustomizableScheme;
@class NMAMapMarker;
@class NMASafetySpot;
@protocol NMAMapGestureDelegate;

/**
 * The Mapping group provides classes, protocols, and enumerations that
 * can be used to enable an interactive map and
 * related functionality, such as creating and adding map objects.
 * Some key classes and protocols in this group are:
 * `NMAMapView`, `NMAMapGestureDelegate`,
 * `NMAMapObject`
 */


#pragma mark - Constants
/**
 * This value may be passed into the map move method
 * `NMAMapView::setGeoCenter:zoomLevel:orientation:tilt:withAnimation:`
 * in place of a zoom, orientation, or tilt value in order to preserve the current value of that property.
 *
 * See also `NMAMapView::setGeoCenter:zoomLevel:orientation:tilt:withAnimation:`
 */
FOUNDATION_EXPORT const float NMAMapViewPreserveValue;

/**
 * The maximum amount that an NMAMapView may be tilted.
 *
 * @note Additional limitations may be placed on the tilt of an NMAMapView using its
 * maximumTiltProfile property.
 */
FOUNDATION_EXPORT const float NMAMapViewMaximumTilt;


#pragma mark - Enums

/**
 * Projection types supported by `NMAMapView`.
 */
typedef NS_ENUM(NSInteger, NMAProjectionType) {
    /** A 2D Mercator projection. */
    NMAProjectionTypeMercator,
    /** A 3D globe projection. */
    NMAProjectionTypeGlobe
};

/**
 * Animation types supported by `NMAMapView`.
 */
typedef NS_ENUM(NSUInteger, NMAMapAnimation) {
    /**
     * Animation zooms in and then out again in a bow-like manner as the map
     * resets to a new position.
     */
    NMAMapAnimationBow,
    /** Animation moves in a linear manner as the map resets to a new position. */
    NMAMapAnimationLinear,
    /** No animation is performed as the map resets to a new position. */
    NMAMapAnimationNone,
    /** brief Animation moves a way that simulates the flight path of a rocket. */
    NMAMapAnimationRocket
};

/**
 * Events generated by `NMAMapView`.
 *
 * See also `NMAMapView::respondToEvents:withBlock:`
 */
typedef NS_OPTIONS(NSInteger, NMAMapEvent) {
    /** The map geoCenter property has changed. */
    NMAMapEventGeoCenterChanged         = 1 << 0,
    /** The map zoomLevel property has changed. */
    NMAMapEventZoomLevelChanged         = 1 << 1,
    /** The map orientation property has changed. */
    NMAMapEventOrientationChanged       = 1 << 2,
    /** The map tilt property has changed. */
    NMAMapEventTiltChanged              = 1 << 3,

    /**
     * The map has begun being transformed from any continuous source, such as gestures
     * or animation. Transformation means that one or more of the geoCenter, zoomLevel,
     * orientation, and tilt properties are being changed.
     *
     * @note This event will not be triggered by explicit assignments to the properties
     * listed above.
     */
    NMAMapEventTransformationBegan      = 1 << 4,
    /** The map has finished being transformed from all sources. */
    NMAMapEventTransformationEnded      = 1 << 5,
    /** A gesture has begun on the map. */
    NMAMapEventGestureBegan             = 1 << 6,
    /** All gestures have ended on the map. */
    NMAMapEventGestureEnded             = 1 << 7,
    /** An animation has begun on the map. */
    NMAMapEventAnimationBegan           = 1 << 8,
    /** An animation has finished on the map. */
    NMAMapEventAnimationEnded           = 1 << 9,

    /** Event occurs when an %NMAMapMarker starts being dragged. */
    NMAMapEventMarkerDragBegan          = 1 << 10,
    /** Event occurs repeatedly while an %NMAMapMarker is being dragged. */
    NMAMapEventMarkerDragged              = 1 << 11,
    /** Event occurs when an %NMAMapMarker has finished being dragged. */
    NMAMapEventMarkerDragEnded          = 1 << 12,

    /** Indicates all map event types. */
    NMAMapEventAll                      = 0xFFFF
};

/**
 * Defines types of ways to display transit operations on a map.
 */
typedef NS_ENUM(NSInteger, NMAMapTransitDisplayMode) {
    /** Hide all transit/train stops, accesses and lines. */
    NMAMapTransitDisplayModeNothing,
    /** (Default) Show transit/train stops and accesses, but hide transit lines. */
    NMAMapTransitDisplayModeStopAndAccess,
    /** Show all transit/train stops, accesses and lines. */
    NMAMapTransitDisplayModeEverything
};

/**
 * Traffic layer type enum mask
 */
typedef NS_OPTIONS(NSInteger, NMATrafficLayer) {
    NMATrafficLayerFlow         = 0x01,
    NMATrafficLayerIncidents    = 0x02,
    NMATrafficLayerOnRoute      = 0x04,
    NMATrafficLayerAll          = 0xFF
};

/**
 * Map layer category type enum
 */
typedef NS_ENUM(NSInteger, NMAMapLayerCategory) {
    /** Land */
    NMAMapLayerCategoryLand,
    /** Water */
    NMAMapLayerCategoryWater,
    /** Labels for oceans */
    NMAMapLayerCategoryLabelOcean,
    /** Labels for seas */
    NMAMapLayerCategoryLabelSea,
    /** Labels for lakes, rivers, canals, etc. */
    NMAMapLayerCategoryLabelWaterOther,
    /** Beach */
    NMAMapLayerCategoryBeach,
    /** Woodland */
    NMAMapLayerCategoryWoodland,
    /** Desert */
    NMAMapLayerCategoryDesert,
    /** Glacier */
    NMAMapLayerCategoryGlacier,
    /** Labels for beaches */
    NMAMapLayerCategoryLabelBeach,
    /** Labels for woodland */
    NMAMapLayerCategoryLabelWoodland,
    /** Labels for deserts */
    NMAMapLayerCategoryLabelDesert,
    /** Labels for glaciers */
    NMAMapLayerCategoryLabelGlacier,
    /** Airport area */
    NMAMapLayerCategoryAirportArea,
    /** Amusement park */
    NMAMapLayerCategoryAmusementPark,
    /** Animal park */
    NMAMapLayerCategoryAnimalPark,
    /** Built-up area */
    NMAMapLayerCategoryBuiltup,
    /** Cemetery */
    NMAMapLayerCategoryCemetery,
    /** Golf course */
    NMAMapLayerCategoryGolfCourse,
    /** Harbor area */
    NMAMapLayerCategoryHarborArea,
    /** Hospital campus */
    NMAMapLayerCategoryHospitalCampus,
    /** Industrial complex */
    NMAMapLayerCategoryIndustrialComplex,
    /** Military base */
    NMAMapLayerCategoryMilitaryBase,
    /** National park */
    NMAMapLayerCategoryNationalPark,
    /** Native reserves */
    NMAMapLayerCategoryNativeReservation,
    /** Military base outline */
    NMAMapLayerCategoryOutlineMilitaryBase,
    /** National park outline */
    NMAMapLayerCategoryOutlineNationalPark,
    /** Native reserves outline */
    NMAMapLayerCategoryOutlineNativeReservation,
    /** City park */
    NMAMapLayerCategoryCityPark,
    /** Pedestrian area */
    NMAMapLayerCategoryPedestrianArea,
    /** Rail yard */
    NMAMapLayerCategoryRailyard,
    /** Shopping complex */
    NMAMapLayerCategoryShoppingComplex,
    /** Sports complex */
    NMAMapLayerCategorySportsComplex,
    /** University campus */
    NMAMapLayerCategoryUniversityCampus,
    /** Airport area labels */
    NMAMapLayerCategoryLabelAirportArea,
    /** Amusement park labels */
    NMAMapLayerCategoryLabelAmusementPark,
    /** Animal park labels */
    NMAMapLayerCategoryLabelAnimalPark,
    /** Cemetery labels */
    NMAMapLayerCategoryLabelCemetery,
    /** Golf course labels */
    NMAMapLayerCategoryLabelGolfCourse,
    /** Harbor area labels */
    NMAMapLayerCategoryLabelHarborArea,
    /** Hospital campus labels */
    NMAMapLayerCategoryLabelHospitalCampus,
    /** Industrial complex labels */
    NMAMapLayerCategoryLabelIndustrialComplex,
    /** Military base labels */
    NMAMapLayerCategoryLabelMilitaryBase,
    /** National park labels */
    NMAMapLayerCategoryLabelNationalPark,
    /** Native reserve labels */
    NMAMapLayerCategoryLabelNativeReservation,
    /** City park labels */
    NMAMapLayerCategoryLabelCityPark,
    /** Pedestrian area labels */
    NMAMapLayerCategoryLabelPedestrianArea,
    /** Rail yard labels */
    NMAMapLayerCategoryLabelRailyard,
    /** Shopping complex labels */
    NMAMapLayerCategoryLabelShoppingComplex,
    /** Sports complex labels */
    NMAMapLayerCategoryLabelSportsComplex,
    /** University campus labels */
    NMAMapLayerCategoryLabelUniversityCampus,
    /** Street of highest importance, for example, national highways */
    NMAMapLayerCategoryStreetCategory0,
    /** Street of 2nd highest importance */
    NMAMapLayerCategoryStreetCategory1,
    /** Street of medium importance */
    NMAMapLayerCategoryStreetCategory2,
    /** Street of 2nd lowest importance */
    NMAMapLayerCategoryStreetCategory3,
    /** Street of lowest importance, for example, small local roads. */
    NMAMapLayerCategoryStreetCategory4,
    /** Pedestrian-friendly streets */
    NMAMapLayerCategoryStreetCategoryPedestrian,
    /** Pedestrian-only streets */
    NMAMapLayerCategoryStreetCategoryWalkway,
    /** Labels for streets included in {@link #NMAMapLayerCategoryStreetCategory0}. */
    NMAMapLayerCategoryLabelStreetCategory0,
    /** Labels for streets included in {@link #NMAMapLayerCategoryStreetCategory1}. */
    NMAMapLayerCategoryLabelStreetCategory1,
    /** Labels for streets included in {@link #NMAMapLayerCategoryStreetCategory2}. */
    NMAMapLayerCategoryLabelStreetCategory2,
    /** Labels for streets included in {@link #NMAMapLayerCategoryStreetCategory3}. */
    NMAMapLayerCategoryLabelStreetCategory3,
    /** Labels for streets included in {@link #NMAMapLayerCategoryStreetCategory4}. */
    NMAMapLayerCategoryLabelStreetCategory4,
    /** Labels for Pedestrian-friendly streets */
    NMAMapLayerCategoryLabelStreetCategoryPedestrian,
    /** Labels for Pedestrian-only streets */
    NMAMapLayerCategoryLabelStreetCategoryWalkway,
    /** Roadside icon */
    NMAMapLayerCategoryRoadsignIcon,
    /** Exit sign */
    NMAMapLayerCategoryExitSign,
    /** Country border */
    NMAMapLayerCategoryBorderCountry,
    /** State border */
    NMAMapLayerCategoryBorderState,
    /** Region border */
    NMAMapLayerCategoryBorderRegional,
    /** Builtup border */
    NMAMapLayerCategoryBorderBuiltup,
    /** Line Of Control border i.e. is an internationally recognized boundary in a disputed area. */
    NMAMapLayerCategoryBorderLineOfControl,
    /** Neighborhood area */
    NMAMapLayerCategoryNeighborhoodArea,
    /** Continent label */
    NMAMapLayerCategoryLabelContinent = 74,
    /** Major country label */
    NMAMapLayerCategoryLabelMajorCountry,
    /** Minor country label */
    NMAMapLayerCategoryLabelMinorCountry,
    /** State label */
    NMAMapLayerCategoryLabelState,
    /** State abbreviation label */
    NMAMapLayerCategoryLabelStateAbbreviation,
    /** National capital city label */
    NMAMapLayerCategoryLabelCityCapital,
    /** Provincial/State capital city label */
    NMAMapLayerCategoryLabelCityStateCapital,
    /** Other cities label */
    NMAMapLayerCategoryLabelCityOther,
    /** Neighborhood area label */
    NMAMapLayerCategoryLabelNeighborhoodArea,
    /** Public transit line */
    NMAMapLayerCategoryPublicTransitLine,
    /** Public transit line label */
    NMAMapLayerCategoryLabelPublicTransitLine,
    /** Public transit icon */
    NMAMapLayerCategoryIconPublicTransitStation,
    /** Public transit label */
    NMAMapLayerCategoryLabelPublicTransitStation,
    /** Relief */
    NMAMapLayerCategoryRelief,
    /** Background */
    NMAMapLayerCategoryBackground,
    /** Mountain label */
    NMAMapLayerCategoryLabelMountain,
    /** Mountain icon */
    NMAMapLayerCategoryIconMountain,
    /** Island label */
    NMAMapLayerCategoryLabelIsland,
    /** Building */
    NMAMapLayerCategoryBuilding,
    /** Building label */
    NMAMapLayerCategoryLabelBuilding,
    /** Point addresses, alphanumeric house-numbers which are assigned to a street segment. */
    NMAMapLayerCategoryPointAddress,
    /** Pedestrian features that includes: crosswalk, stairs, escalator, elevator, tunnel, and bridge */
    NMAMapLayerCategoryPedestrianFeature,
    /** Railroad */
    NMAMapLayerCategoryRailroad,
    /** Ferry */
    NMAMapLayerCategoryFerry,
    /** Ferry label */
    NMAMapLayerCategoryLabelFerry,
    /** POI icon */
    NMAMapLayerCategoryPoiIcon,
    /** POI label */
    NMAMapLayerCategoryPoiLabel,
    /** Category count */
    NMAMapLayerCategoryCount,
    /** Category None */
    NMAMapLayerCategoryNone
};

/**
 * Defines POI (Point of Interest) categories.
 */
typedef NS_ENUM(NSInteger, NMAMapPoiCategory) {
    /** Airline access points. */
    NMAMapPoiCategoryAirLineAccess,
    /** Amusement parks. */
    NMAMapPoiCategoryAmusementPark,
    /** Car dealerships. */
    NMAMapPoiCategoryCarDealer,
    /** Casinos. */
    NMAMapPoiCategoryCasino,
    /** Movie houses. */
    NMAMapPoiCategoryCinema,
    /** Companies. */
    NMAMapPoiCategoryCompany,
    /** Concert halls. */
    NMAMapPoiCategoryConcertHall,
    /** Congressional houses. */
    NMAMapPoiCategoryCongress,
    /** Courthouses. */
    NMAMapPoiCategoryCourthouse,
    /** Cultural centers. */
    NMAMapPoiCategoryCulturalCentre,
    /** Exhibition centers. */
    NMAMapPoiCategoryExhibitionCentre,
    /** Golf courses. */
    NMAMapPoiCategoryGolfCourse,
    /** Government offices. */
    NMAMapPoiCategoryGovernmentOffice,
    /** Holiday parks. */
    NMAMapPoiCategoryHolidayPark,
    /** Museums. */
    NMAMapPoiCategoryMuseum,
    /** Opera houses. */
    NMAMapPoiCategoryOpera,
    /** Parking garages. */
    NMAMapPoiCategoryParkingGarage,
    /** Gas stations. */
    NMAMapPoiCategoryPetrolStation,
    /** Churches and other places of worship. */
    NMAMapPoiCategoryPlaceOfWorship,
    /** Post offices. */
    NMAMapPoiCategoryPostOffice,
    /** Car rental facilities. */
    NMAMapPoiCategoryRentACarFacility,
    /** Rest areas. */
    NMAMapPoiCategoryRestArea,
    /** Restaurants. */
    NMAMapPoiCategoryRestaurant,
    /** Shops. */
    NMAMapPoiCategoryShop,
    /** Shopping centers. */
    NMAMapPoiCategoryShoppingCentre,
    /** Stadiums. */
    NMAMapPoiCategoryStadium,
    /** Theaters. */
    NMAMapPoiCategoryTheatre,
    /** Tourist attractions. */
    NMAMapPoiCategoryTouristAttraction,
    /** Tourist information centers. */
    NMAMapPoiCategoryTouristInformationCentre,
    /** Universities. */
    NMAMapPoiCategoryUniversity,
    /** Zoos. */
    NMAMapPoiCategoryZoo,
    /** Libraries. */
    NMAMapPoiCategoryLibrary,
    /** Camping grounds. */
    NMAMapPoiCategoryCamping,
    /** Bars and discos. */
    NMAMapPoiCategoryBarDisco,
    /** Embassies. */
    NMAMapPoiCategoryEmbassy,
    /** Ferry terminals. */
    NMAMapPoiCategoryFerryTerminal,
    /** Frontier crossings. */
    NMAMapPoiCategoryFrontierCrossing,
    /** Hospitals. */
    NMAMapPoiCategoryHospital,
    /** Hotels. */
    NMAMapPoiCategoryHotel,
    /** Parking areas (lots). */
    NMAMapPoiCategoryParkingArea,
    /** Police stations. */
    NMAMapPoiCategoryPolice,
    /** Railway stations. */
    NMAMapPoiCategoryRailwayStation,
    /** Metro (subway) stations. */
    NMAMapPoiCategoryMetroStation,
    /** Airports. */
    NMAMapPoiCategoryAirport,
    /** Mountain passes. */
    NMAMapPoiCategoryMountainPass,
    /** Mountain peaks. */
    NMAMapPoiCategoryMountainPeak,
    /** Car repair businesses. */
    NMAMapPoiCategoryCarrepair,
    /** Cash dispensers (banking machines). */
    NMAMapPoiCategoryCashDispenser,
    /** Parks and similar recreation areas. */
    NMAMapPoiCategoryParkRecreation,
    /** Pharmacies. */
    NMAMapPoiCategoryPharmacy,
    /** Beaches. */
    NMAMapPoiCategoryBeach,
    /** Bus stations. */
    NMAMapPoiCategoryBusStation = 57,
    /** Education facilities. */
    NMAMapPoiCategoryEducation = 106,
    /** Residential areas. */
    NMAMapPoiCategoryResidentialArea = 117,
    /** EV Charging station. */
    NMAMapPoiCategoryEVChargingStation  = 196,
    /** Nightclubs. */
    NMAMapPoiCategoryNightClub = 203,
    /** Public washrooms. */
    NMAMapPoiCategoryPublicToilet = 204,
    /** Laundries. */
    NMAMapPoiCategoryLaundry = 207,
    /** Taxi stands. */
    NMAMapPoiCategoryTaxiStand = 216,
    /** Railway access points. */
    NMAMapPoiCategoryRailwayAccess = 217,
    /** Bars and cafes. */
    NMAMapPoiCategoryBarsCafes = 218,
    /** Parking areas (street). */
    NMAMapPoiCategoryParking = 219,
    /** Outdoor sport venues. */
    NMAMapPoiCategorySportOutdoor = 220,
    /** Metro access. */
    NMAMapPoiCategoryMetroAccess = 221,
    /** Metro access points in Austria. */
    NMAMapPoiCategoryAutMetroAccess = 222,
    /** Metro stops in Austria. */
    NMAMapPoiCategoryAutMetroStop = 223,
    /** Metro access points in Belgium. */
    NMAMapPoiCategoryBelMetroAccess = 224,
    /** Metro stops in Belgium. */
    NMAMapPoiCategoryBelMetroStop = 225,
    /** Metro access points in Czech Republic. */
    NMAMapPoiCategoryCzeMetroAccess = 226,
    /** Metro stops in Czech Republic. */
    NMAMapPoiCategoryCzeMetroStop = 227,
    /** Metro access points in Denmark. */
    NMAMapPoiCategoryDenMetroAccess = 228,
    /** Metro stops in Denmark. */
    NMAMapPoiCategoryDenMetroStop = 229,
    /** Metro access points in Finland. */
    NMAMapPoiCategoryFinMetroAccess = 230,
    /** Metro stops in Finland. */
    NMAMapPoiCategoryFinMetroStop = 231,
    /** Metro access points in France. */
    NMAMapPoiCategoryFraMetroAccess = 232,
    /** Metro stops in France. */
    NMAMapPoiCategoryFraMetroStop = 233,
    /** RER access points in France. */
    NMAMapPoiCategoryFraRerAccess = 234,
    /** RER stops in France. */
    NMAMapPoiCategoryFraRerStop = 235,
    /** Metro access points in Germany. */
    NMAMapPoiCategoryDeuMetroAccess = 236,
    /** Metro stops in Germany. */
    NMAMapPoiCategoryDeuMetroStop = 237,
    /** S-Bahn access points in Germany. */
    NMAMapPoiCategoryDeuSbahnAccess = 238,
    /** S-Bahn stops in Germany. */
    NMAMapPoiCategoryDeuSbahnStop = 239,
    /** Metro access points in Italy. */
    NMAMapPoiCategoryItaMetroAccess = 240,
    /** Metro stops in Italy. */
    NMAMapPoiCategoryItaMetroStop = 241,
    /** Metro access points in Norway. */
    NMAMapPoiCategoryNorMetroAccess = 242,
    /** Metro stops in Norway. */
    NMAMapPoiCategoryNorMetroStop = 243,
    /** Metro access points in Portugal. */
    NMAMapPoiCategoryPrtMetroAccess = 244,
    /** Metro stops in Portugal. */
    NMAMapPoiCategoryPrtMetroStop = 245,
    /** Metro access points in Barcelona. */
    NMAMapPoiCategoryEspBarcelonaMetroAccess = 246,
    /** Metro stops in Barcelona. */
    NMAMapPoiCategoryEspBarcelonaMetroStop = 247,
    /** Metro access points in Cercanias. */
    NMAMapPoiCategoryEspCercaniasMetroAccess = 248,
    /** Metro stops in Cercanias. */
    NMAMapPoiCategoryEspCercaniasMetroStop = 249,
    /** Metro access points in Madrid. */
    NMAMapPoiCategoryEspMadridMetroAccess = 250,
    /** Metro stops in Madrid. */
    NMAMapPoiCategoryEspMadridMetroStop = 251,
    /** Metro access points in Sweden. */
    NMAMapPoiCategorySweMetroAccess = 252,
    /** Metro stops in Sweden. */
    NMAMapPoiCategorySweMetroStop = 253,
    /** Metro access points in Glasgow. */
    NMAMapPoiCategoryGbrGlasgowMetroAccess = 254,
    /** Metro stops in Glasgow. */
    NMAMapPoiCategoryGbrGlasgowMetroStop = 255,
    /** Metro access points in London. */
    NMAMapPoiCategoryGbrLondonMetroAccess = 256,
    /** Metro stops in London. */
    NMAMapPoiCategoryGbrLondonMetroStop = 257,
    /** All points of interest. */
    NMAMapPoiCategoryAll  = 258
};


#pragma mark - Types

/**
 * Defines a block type used to implement a function that provides a tilt value
 * output for a zoom level input.
 *
 * Tilt/zoom profiles are used to control the minimum and maximum tilt allowed on a map
 * view at a given zoom level. The block takes an input zoom level that will be in the
 * range [NMAMapViewMinimumZoomLevel, NMAMapViewMaximumZoomLevel]. The output should be
 * a tilt value in the range [0, NMAMapViewMaximumTilt].
 *
 * See also `maximumTiltProfile`
 */
typedef float (^NMATiltZoomProfile)(float zoomLevel);

/**
 * Used to provide custom responses to map events.
 *
 * NMAMapEventBlocks are used with the
 * `NMAMapView::respondToEvents:withBlock:`
 * method
 * to provide custom event handling behaviour. Refer to the documentation of that
 * method for more information.
 *
 * @param event The type of the event that has occurred.
 * @param mapView The map view which generated the event.
 * @param eventData An optional object containing information about the event.
 *
 * @return YES if the block should continue to handler the input event type, NO if it
 * should not.
 *
 * See also `NMAMapView::respondToEvents:withBlock:`
 * See also `NMAMapEvent`
 */
typedef BOOL (^NMAMapEventBlock)(NMAMapEvent event, NMAMapView * _Nonnull mapView, id _Nullable eventData);

#pragma mark -

/**
 * Represents a delegate that offers listeners and callback methods related to
 * visible actions that result from user interaction.
 *
 * @note Methods of this protocol are called on the main queue.
 */
@protocol NMAMapViewDelegate<NSObject>
@optional
/**
 * A callback indicating that `NMAViewObject` objects have been
 * selected.
 *
 * @param mapView The NMAMapView instance sending the callback
 * @param objects A `NSArray` of selected objects
 */
- (void)mapView:(nonnull NMAMapView *)mapView didSelectObjects:(nonnull NSArray<NMAViewObject *> *)objects
NS_SWIFT_NAME(mapView(_:didSelect:));

/**
 * A callback indicating that a map movement has begun due to user
 * interaction.
 *
 * This callback will be sent at the start of the gesture when the map is
 * panned, tilted, pinch zoomed, or rotated (only for user gestures).
 *
 * @note If the map receives more than one of these gestures at the same time,
 * only a single callback will be sent until all map movement has stopped.
 */
- (void)mapViewDidBeginMovement:(nonnull NMAMapView *)mapView;

/**
 * A callback indicating that a map movement has ended.
 *
 * @note There will be a one-to-one correspondence with this callback and the
 * mapViewDidBeginMovement callback.
 */
- (void)mapViewDidEndMovement:(nonnull NMAMapView *)mapView;

/**
 *  A callback indicating the beginning of an animation on the map.
 *
 * This is fired after one of the following operations starts:
 *
 * 1. setting the map center (with animation). E.g. with `NMAMapView#setCenter:`
 *
 * 2. setting the map orientation (with animation). E.g. with `NMAMapView#setOrientation:`
 *
 * 3. setting the map tilt (with animation). E.g. with `NMAMapView#setTilt:`
 *
 * 4. setting the map zoom level (with animation). E.g. with `NMAMapView#setZoomLevel:`
 */
- (void)mapViewDidBeginAnimation:(nonnull NMAMapView *)mapView;

/**
 * A callback indicating the end of an animation on the map.
 *
 * This is fired after one of the following operations ends:
 *
 * 1. setting the map center (with animation). E.g. with `NMAMapView#setCenter:`
 *
 * 2. setting the map orientation (with animation). E.g. with `NMAMapView#setOrientation:`
 *
 * 3. setting the map tilt (with animation). E.g. with `NMAMapView#setTilt:`
 *
 * 4. setting the map zoom level (with animation). E.g. with `NMAMapView#setZoomLevel:`
 */
- (void)mapViewDidEndAnimation:(nonnull NMAMapView *)mapView;

/**
 * A callback indicating that map data has been drawn.
 */
- (void)mapViewDidDraw:(nonnull NMAMapView *)mapView;

/**
 * A callback indicating that the map has been drawn to a bitmap by the software renderer.
 *
 * This method will not be called if the softwareRenderToBitmap property is set to NO or if
 * software rendering is not currently active. See the softwareRenderToBitmap property for
 * more information.
 *
 * IMPORTANT: Software Rendering is a Beta feature, and associated methods and behaviours
 * are subject to change without notice.
 *
 * @note This method is called on NMAMapView's render thread and not the main thread. Spending a
 * lot of time in this callback will degrade map rendering performance.
 *
 * @param mapView The NMAMapView instance sending the callback.
 * @param bitmap Bitmap data in the NMAPixelFormatRGBA format.
 *               IT IS ONLY SAFE TO ACCESS THE BITMAP IN THE CONTEXT OF THIS CALLBACK.
 * @param width Width of the bitmap in pixels.
 * @param height Height of the bitmap in pixels.
 * @param bytesPerPixel Number of bytes used to represent the color of each pixel.
 */
- (void)mapView:(nonnull NMAMapView *)mapView
didRenderBitmap:(nonnull void*)bitmap
      withWidth:(NSUInteger)width
         height:(NSUInteger)height
  bytesPerPixel:(NSUInteger)bytesPerPixel
NS_SWIFT_NAME(mapView(_:didRender:width:height:bytesPerPixel:));

/**
 * A callback indicating that a user has performed a single-tap gesture on an safety spot
 * icon.
 *
 * @param mapView The NMAMapView instance sending the callback.
 * @param info Contains information about a particular safety spot.
 */
- (void)mapView:(nonnull NMAMapView *)mapView didTapOnSafetySpot:(nonnull NMASafetySpot *)info
NS_SWIFT_NAME(mapView(_:didTapOnSafetySpot:));

@end

#pragma mark -


/**
 *
 * A UIView subclass used by an application to display a geographical map.
 *
 * The NMAMapView will recognize and respond to a number of different gestures,
 * which are described by the NMAMapGestureType enum. Subviews of the map may
 * optionally receive these gestures instead of the map (see NMAMapGestureDelegate).
 *
 * NMAMapView requires valid authentication credentials to be set via
 * NMAApplicationContext. If valid credentials are not present the API may not
 * function correctly or may stop functioning correctly in the future when server
 * side configurations change.
 *
 * @note Views which depend on receiving touch events (such as UIButton) should not
 * be installed as NMAMapView subviews, but rather as siblings in the view hierarchy.
 */
@interface NMAMapView : UIView

#pragma mark Setup

/**
 * Used to control the default `NMAMapView` rendering behaviour.
 *
 * This class method is used to set whether or not instances of `NMAMapView` will
 * begin rendering immediately upon creation. Any map view created after passing
 * NO to this method must have its renderAllowed property set to YES to begin
 * rendering.
 */
+ (void)shouldBeginRenderingAutomatically:(BOOL)enabled;

/**
 * Default initializer of a `NMAMapView`.
 *
 * 1. The `NMAMapView` must have a container view.
 *
 * 2. Use the -[NMAMapView initWithFrame:] method with the frame acting as the
 * bounds of the container view.
 *
 * 3. The container view must have its property autoresizesSubviews = YES.
 *
 * 4. The map view must have its property autoresizingMask =
 * UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight
 *
 * Example:
 *
 * \code
 *
 * IBOutlet UIView* _parentOfMapView; // Parent view is necessary to set the correct z-order.
 * NMAMapView* mapView;
 * ---
 * mapView = [[NMAMapView alloc] initWithFrame:_parentOfMapView.frame];
 * [_parentOfMapView addSubview:mapView];
 *
 * _parentOfMapView.autoresizesSubviews = YES;
 * mapView.autoresizingMask = UIViewAutoresizingFlexibleWidth |
 * UIViewAutoresizingFlexibleHeight;
 * \endcode
 *
 * If the frame of the NMAMapView is much larger than the main window
 * of the UIApplication its rendering will be very slow and could give the impression of a frozen UI.
 *
 * @return A `NMAMapView`.
 *
 * @note The view will not render anything if there are configuration errors -
 * see `NMACustomConfigurations` for more details.
 */
- (nonnull instancetype)initWithFrame:(CGRect)frame;

#pragma mark Behavior

/**
 * A flag which can be used to allow or disallow map rendering.
 *
 * Setting renderAllowed to NO guarantees that the map will not draw
 * again (but it will finish if a frame is in the middle of rendering), but
 * the map may not redraw with renderAllowed set to YES if it is prevented
 * from drawing for another reason.
 *
 * The map can be hinted to redraw (if allowed) by calling setNeedsDisplay.
 */
@property (nonatomic, getter = isRenderAllowed) BOOL renderAllowed;

/**
 * Controls whether the map view automatically pauses rendering when the
 * willResignActive notification is received.
 *
 * If pauseOnWillResignActive is set to NO, it is highly recommended that the
 * mapView renderAllowed property is set to NO before the application delegate
 * didEnterBackground method returns.
 *
 * The default value is YES.
 */
@property (nonatomic) BOOL pauseOnWillResignActive;

/**
 * If enabled, the value returned by `NMAMapView::maximumRefreshRate` will
 * be the maximum refresh rate in all scenarios (including navigation).
 *
 * Defaults to NO.
 *
 * IMPORTANT: Configurable refresh rate is a Beta feature, and associated methods
 * and behaviours are subject to change without notice.
 */
@property (nonatomic) BOOL maximumRefreshRateLimitEnabled;

/**
 * The maximum refresh rate of the map view in frames per second.
 *
 * Getting this property will return the current maximum refresh rate. The default value is
 * currently 60 FPS during non-navigation but is lower during navigation - See
 * `NMANavigationManager::backgroundMapTrackingMaximumRefreshRate`
 *
 * If `NMAMapView::maximumRefreshRateLimitEnabled` is set to YES, the value
 * specified will be used in all scenarios (including navigation). This may result in higher
 * CPU usage and higher power usage during navigation. Contact your HERE representative for
 * more information.
 *
 * This property must be in the range 1..60. Values outside this range will be ignored.
 *
 * Defaults to 60 FPS.
 *
 * IMPORTANT: Configurable refresh rate is a Beta feature, and associated methods
 * and behaviours are subject to change without notice.
 *
 * @note Gestures do not work well at low frames rates - i.e. they feel very unresponsive.
 */
@property (nonatomic) float maximumRefreshRate;

/**
 * An event handler for the `NMAMapView`.
 *
 * An object may be installed as the `NMAMapView`'s delegate in order to respond
 * to certain map events, such as object selection or map movement. See the
 * `NMAMapViewDelegate` protocol for the full list of events.
 */
@property (nonatomic, weak, nullable) id<NMAMapViewDelegate> delegate;

/**
 * Provides a block of code to be executed upon the occurrence of one or more
 * map events.
 *
 * While using an NMAMapView, an application might need to respond to certain map
 * events that occur, such as map transformations or the beginning or ending of map
 * gestures or animations. This method provides a mechanism by which an application
 * may provide an arbitrary block of code to be executed in response to certain map
 * events.
 *
 * The same block may be used to respond to multiple events. The parameters passed to
 * the event block include the event type, the map which generated the event, and
 * optional event data. The event block returns a BOOL to indicate whether the block
 * should continue to respond to the given event type. If a block no longer responds
 * to any events, it is destroyed.
 *
 * Each block is assigned a unique integer identifier, returned by this method. The
 * identifier may be used to stop the block from responding to events without waiting
 * for those events to be triggered, using the method
 * `NMAMapView::removeEventBlockWithIdentifier:`.
 *
 * When creating event handler blocks, care should be taken to avoid retain cycles.
 * Any objects strongly referenced in the block will never be released as long as the
 * block remains. This includes any explicit or implicit (e.g. through an instance
 * variable) references to self. Ensure that any strongly referenced objects inside
 * the block are meant to live as long as the block does; if not, use a weak reference.
 *
 * Blocks which respond to frequent events (e.g. `NMAMapEventGeoCenterChanged`)
 * should not perform any CPU-intensive work to avoid performance degradation.
 *
 * @note Event blocks will always be invoked on the application's main thread.
 *
 * @param events A bit-wise OR combination of NMAMapEvent values.
 * @param block The NMAMapEventBlock to respond to the given events.
 *
 * @return A unique integer value to identify the block.
 *
 * See also `NMAMapEvent`
 *
 * See also `NMAMapView::removeEventBlockWithIdentifier:`
 */
- (NSInteger)respondToEvents:(NMAMapEvent)events withBlock:(nonnull NMAMapEventBlock)block
NS_SWIFT_NAME(respond(to:_:));

/**
 * Removes the event block with the given identifier.
 *
 * To explicitly control when an event block is removed from the map, the
 * identifier returned by
 * `NMAMapView::respondToEvents:withBlock:`
 * should be stored until needed and then passed to this method.
 *
 * @return YES if the block was successfully removed, NO otherwise.
 *
 * @note Do not call this method from inside the block to which the identifier is assigned.
 */
- (BOOL)removeEventBlockWithIdentifier:(NSInteger)identifier
NS_SWIFT_NAME(removeEventBlock(blockIdentifier:));

#pragma mark Appearance

/**
 * The `CGRect` representing the `NMAMapView` clipping rectangle.
 *
 * This property allows the user to restrict the rendered size of the NMAMapView
 * without changing its frame size. The area outside the bounds of the
 * `CGRect` is colored in the default map background color.
 *
 * This property should be used when a known fixed region of the `NMAMapView` will
 * be obscured for a significant amount of time, such as by a subview or popup menu.
 *
 * @note The clipRect is not allowed to exceed the bounds of the `NMAMapView` frame,
 * and the supplied CGRect will be clipped as necessary to ensure this. If a value
 * is supplied which does not overlap the map frame, the clipRect is not changed.
 */
@property (nonatomic) CGRect clipRect;

/**
 * The `NMAGeoBoundingBox` representing the current screen area of the
 * NMAMapView.
 *
 * The boundingBox of the map is the smallest possible NMAGeoBoundingBox which
 * contains all of the map area currently visible on the screen. If the map is
 * in 2D view (zero tilt), the boundingBox should (nearly) exactly coincide
 * with the bounds of the screen rect. If the map is in 3D view, the visible
 * screen area is a trapezoid in geographical space (the visible area is wider
 * at the top of the screen than at the bottom due to perspective). Thus, the
 * bounding box will contain some area that is not actually visible on the
 * screen in this case.
 *
 * The property will be nil If the boundingBox cannot be calculated
 * (e.g. it can happen on low zoom levels).
 *
 * @note The bounding box may be slightly inaccurate if the method is
 * invoked while the map is moving.
 */
@property (nonatomic, readonly, weak, nullable) NMAGeoBoundingBox *boundingBox;

/**
 * The scheme for the `NMAMapView`.
 *
 * @note Not all schemes from `NMAMapScheme` collection are supported if
 * `NMAMapVariantChina` is selected. Before using this property, developer
 * must retrieve all available schemes using `availableMapSchemes`.
 *
 * See also `availableMapSchemes`.
 */
@property (nonatomic, strong, nonnull) NSString *mapScheme;

/**
 * Returns list of available schemes for the map.
 *
 * See also `mapScheme`.
 */
@property (nonatomic, nonnull, readonly) NSArray<NSString *> *availableMapSchemes;

/**
 * The projection method used to display the map.
 *
 * The default projection type is NMAProjectionTypeGlobe.
 *
 * See also `NMAProjectionType`
 */
@property (nonatomic) NMAProjectionType projectionType;

/**
 * The position indicator for the `NMAMapView`.
 */
@property (nonatomic, readonly, nonnull) NMAPositionIndicator *positionIndicator;

/**
 * Indicates 3D landmark visibility for the `NMAMapView`.
 *
 * Landmarks not visible if access to this operation is denied.
 * Contact your HERE representative for more information.
 */
@property (nonatomic) BOOL landmarksVisible;


/**
 * Show fleet features of the specified type on the map.
 *
 * By default all fleet features are hidden.
 *
 * @param fleetFeature NMAMapFleetFeatureType to show.
 */
- (void)showFleetFeature:(NMAMapFleetFeatureType)fleetFeature
NS_SWIFT_NAME(show(fleetFeature:));

/**
 * Hide fleet features of the specified type from the map.
 *
 * By default all fleet features are hidden.
 *
 * @param fleetFeature NMAMapFleetFeatureType to hide.
 */
- (void)hideFleetFeature:(NMAMapFleetFeatureType)fleetFeature
NS_SWIFT_NAME(hide(fleetFeature:));

/**
 * Returns whether a fleet feature type is set to be shown on the map.
 *
 * By default all fleet features are hidden.
 *
 * @param fleetFeature NMAMapFleetFeatureType to query.
 * @return YES if fleet features of the type specified are set to be shown on the map.
 */
- (BOOL)isFleetFeatureShown:(NMAMapFleetFeatureType)fleetFeature
NS_SWIFT_NAME(isShown(fleetFeature:));

/**
 * Access venue3d map layer.
 *
 * See also `NMAVenue3dMapLayer`
 *
 */
@property (nonatomic, readonly, nullable) NMAVenue3dMapLayer *venue3dMapLayer;

/**
 * Create a customizable Scheme. Please note this change is not permanently saved and valid
 * only with application life cycle.
 *
 * @note This method is not supported if current map variant is `NMAMapVariantChina`,
 * in that case nil is returned.
 *
 * @param schemeName
 *            Name of the new scheme which you want to create.
 *
 * @param baseSchemeName
 *            Name of base scheme. New scheme will be derived from this base scheme.
 * @return NMACustomizableScheme instance, or nil if the creation failed.
 *
 * @note Creating a scheme may fail if the provided name was already used, or if deriving from a base
 * scheme which does not exist.
 */
- (nullable NMACustomizableScheme *)createCustomizableSchemeWithName:(nonnull NSString *)schemeName basedOnScheme:(nonnull NSString *)baseSchemeName
NS_SWIFT_NAME(createCustomizableScheme(_:basedOn:));

/**
 * Returns an `NMACustomizableScheme` object that points to an existing custom scheme of the given name.
 *
 * @param schemeName the respective name of the scheme.
 *
 * @note The custom scheme must have been previously created with method
 * `NMAMapView::createCustomizableSchemeWithName:basedOnScheme:`
 * otherwise it will fail returning nil.
 */
- (nullable NMACustomizableScheme *)getCustomizableSchemeWithName:(nonnull NSString *)schemeName
NS_SWIFT_NAME(getCustomizableScheme(_:));

/**
 * Removes the custom scheme with the specified name from the map
 *
 * @param schemeName The respective name of the scheme.
 * @return BOOL True if succeeds, False if failed.
 *
 * @note This reverts the operation from
 * `NMAMapView::createCustomizableSchemeWithName:basedOnScheme:`.
 */
- (BOOL)removeCustomizableSchemeWithName:(nonnull NSString *)schemeName
NS_SWIFT_NAME(removeCustomizableScheme(_:));

/**
 * Show pedestrian features of the specified type on the map.
 *
 * By default all pedestrian features are hidden.
 *
 * @param pedestrianFeature NMAMapPedestrianFeatureType to show.
 *
 * @note Even if pedestrian features are set to be shown they will not actually be rendered if the
 * mapScheme property is set to a "Car Navaigation" scheme (e.g. NMAMapSchemeCarNavigationDay).
 */
- (void)showPedestrianFeature:(NMAMapPedestrianFeatureType)pedestrianFeature
NS_SWIFT_NAME(show(pedestrianFeature:));

/**
 * Hide pedestrian features of the specified type from the map.
 *
 * By default all pedestrian features are hidden.
 *
 * @param pedestrianFeature NMAMapPedestrianFeatureType to hide.
 */
- (void)hidePedestrianFeature:(NMAMapPedestrianFeatureType)pedestrianFeature
NS_SWIFT_NAME(hide(pedestrianFeature:));

/**
 * Returns whether a pedestrian feature type is set to be shown on the map, whether the
 * feature is actually rendered is dependent on the mapScheme property.
 *
 * By default all pedestrian features are hidden.
 *
 * @param pedestrianFeature NMAMapPedestrianFeatureType to query.
 * @return YES if pedestrian features of the type specified are set to be shown on the map.
 *
 * @note Even if pedestrian features are set to be shown they will not actually be rendered if the
 * mapScheme property is set to a "Car Navigation" scheme (e.g. NMAMapSchemeCarNavigationDay).
 */
- (BOOL)isPedestrianFeatureShown:(NMAMapPedestrianFeatureType)pedestrianFeature
NS_SWIFT_NAME(isShown(pedestrianFeature:));

/**
 * Set the visibility of the map layer categories to be rendered.
 *
 * The layer categories are specified using the NMAMapLayerCategory enum.
 *
 * Only the specified map layer categories visibility are changed, the
 * visibility of all other map layer categories will remain the same.
 *
 * @param visible YES to make map layer categories visible, NO to hide.
 * @param layerCategories An array of NSNumber objects containing NMAMapLayerCategory values.
 */
- (void)setVisibility:(BOOL)visible forMapLayerCategories:(nonnull NSArray<NSNumber *> *)layerCategories
NS_SWIFT_NAME(setVisibility(_:for:));

/**
 * Get the set of visible map layer categories.
 *
 * @return An NSArray of NSNumber objects containing the NMAMapLayerCategory values.
 */
- (nonnull NSArray<NSNumber *> *)visibleMapLayerCategories;


/**
 * Indicates if safety spots are visible on the map.
 *
 * Defaults to NO.
 *
 * Safety spots can not be set visible if access to this operation is denied.
 * Contact your HERE representative for more information.
 */
@property (nonatomic) BOOL safetySpotsVisible;

/**
 * Check the visibility of a specific map layer category.
 *
 * @param layerCategory A specific map layer category.
 * @return YES if the map layer category is visible, NO otherwise.
 */
- (BOOL)isMapLayerCategoryVisible:(NMAMapLayerCategory)layerCategory
NS_SWIFT_NAME(isVisible(_:));

/**
 * Set the visibility of a specific POI on the map.
 *
 * NMAMapPoiCategoryAll may be used to show or hide all POIs.
 *
 * @param visible YES if POI is visible, NO otherwise.
 * @param poiCategory A specific POI category.
 * @return YES if enable or disable POI category successfully, NO otherwise.
 */
- (BOOL)setVisibility:(BOOL)visible forPoiCategory:(NMAMapPoiCategory)poiCategory
NS_SWIFT_NAME(setVisibility(_:for:));

/**
 * Check the visibility of a specific POI on the map.
 *
 * @param poiCategory A specific POI category.
 * @return YES if POI is visible, NO otherwise.
 */
- (BOOL)isPoiCategoryVisible:(NMAMapPoiCategory)poiCategory;

/**
 * Get the list of poi categories.
 *
 * @return A list of NSStrings.
 */
- (nonnull NSArray<NSString *> *)poiCategories;

/**
 * Control whether or not extruded buildings are visible on the map.
 *
 * If set to YES, extruded buildings will be shown on the map. NO otherwise.
 */
@property (nonatomic, readwrite) BOOL extrudedBuildingsVisible;

#pragma mark - Language

/**
 * Set the map display language using the device preferred language.
 *
 * @return True if the language is accepted by the map, false otherwise.
 *
 * @note If it fails, the map display language reverts to the default language which is English (en).
 */
- (BOOL)useDefaultDisplayLanguage;

/**
 * Set the map display language using the locale specified.
 *
 * @param locale The NSLocale as described in the official Apple documentation at
 *               https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSLocale_Class/
 *
 * @return True if the locale is accepted by the map and false otherwise.
 *
 * @note If it fails, the map display language reverts to the default language which is English (en).
 */
- (BOOL)useDisplayLanguageFromLocale:(nonnull NSLocale *)locale
NS_SWIFT_NAME(useDisplayLanguage(fromLocale:));

/**
 * The language which the map is set to render.
 *
 * @note It is nil if the display language isn't set and the default language English (en) is being used.
 */
@property (nonatomic, readonly, weak, nullable) NSString *displayLanguage;

/**
 * Set the secondary map display language using the locale specified.
 *
 * Setting a secondary display language will cause the language to be displayed below the
 * primary language for some map labels (e.g. countries).
 *
 * @param locale The NSLocale as described in the official Apple documentation at
 *               https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSLocale_Class/
 *               Pass nil if you want to remove the secondary map display language.
 *
 * @return True if the locale is accepted by the map and false otherwise.
 *
 * @note If it fails, the secondary map display language reverts to the last valid one.
 */
- (BOOL)useSecondaryDisplayLanguageFromLocale:(nullable NSLocale *)locale
NS_SWIFT_NAME(useSecondaryDisplayLanguage(fromLocale:));

/**
 * The secondary language which the map is set to render.
 *
 * @note It is nil if the secondary display language isn't set which is the default behaviour.
 */
@property (nonatomic, readonly, weak, nullable) NSString *secondaryDisplayLanguage;

/**
 * Get the list of supported display languages.
 *
 * @return Array of supported display languages.
 */
- (nonnull NSArray<NSString *> *)supportedDisplayLanguages;

#pragma mark Gestures

/**
 * An optional delegate to process gestures on behalf of the map view.
 *
 * Replace this property with a custom class implementing the NMAMapGestureDelegate
 * protocol to customize the gesture response behaviour of the map. Set to nil
 * to restore the original gesture behaviour.
 *
 * See also `NMAMapGestureDelegate`
 */
@property (nonatomic, weak, nullable) id<NMAMapGestureDelegate> gestureDelegate;

/**
 * Provides default gesture handling behaviour for the NMAMapView from
 * within a custom gesture handling method.
 *
 * The gestureHandler can be used to perform
 * default gesture actions in addition to the gestureDelegate's custom
 * behaviour.
 *
 * Default actions are performed by calling the appropriate gesture handling
 * method from within the gestureDelegate's custom implementation of that method.
 * For example, to perform the default tap action in addition to custom behaviour,
 * implement the NMAMapGestureDelegate method in your gestureDelegate class as follows:
 *
 * \code
 *  -(void)mapView:(NMAMapView *)mapView didReceiveTapAtLocation:(CGPoint)location
 *  {
 *      // Some custom behaviour...
 *      [mapView.defaultGestureHandler mapView:mapView didReceiveTapAtLocation:location];
 *      // More custom behaviour...
 *  }
 * \endcode
 */
@property (nonatomic, readonly, nullable) id<NMAMapGestureDelegate> defaultGestureHandler;

/**
 * Indicates the state of enabling and modifying map gesture interaction
 * for the `NMAMapView`.
 *
 * If enabled, gesture handlers can be enabled to begin gesture handling. If
 * disabled, all gesture handling is disabled and the gesture handler state
 * cannot be modified.
 */
@property (nonatomic, getter = isMapInteractionEnabled) BOOL mapInteractionEnabled;

/**
 * The touch duration required to trigger a long press gesture.
 *
 * The default value is 1 second.
 */
@property (nonatomic) NSTimeInterval longPressDuration;

/**
 * Indicates whether the transform center is used on rotate and zoom gestures.
 *
 * By default disabled. If enabled, rotation and zoom will always be applied using
 * the current transform center, instead of a point relative the touch interaction.
 *
 * @note The transform center is usually the same as the screen's geometric center,
 * except in cases where it makes sense to have it slightly modified (example: in
 * guidance mode, the transform center is lowered a bit so that the route ahead
 * is more visible in the map view).
 */
@property (nonatomic) BOOL mapCenterFixedOnRotateZoom;

/**
 * Controls which two-finger pan direction increases the tilt value of the `NMAMapView`.
 *
 * If YES, a two-finger pan gesture from the bottom to the top of the map will
 * increase the tilt angle. In other words, the viewing angle changes to a more apparent
 * 3D view.
 *
 * If NO, such a gesture will decrease the tilt angle.
 *
 * The default value is NO.
 */
@property (nonatomic) BOOL upwardPanIncreasesTilt;

/**
 * Enables changing the tilt angle of the `NMAMapView` using a two finger pan.
 *
 * If YES, a two-finger pan with horizontal finger placement and vertical pan
 * direction will change the tilt angle.
 *
 * If NO, all two-finger pans will be treated the same as one-finger pans by
 * default. Custom two-finger pan behavior can still be implemented using
 * NMAMapGestureDelegate.
 *
 * The default value is YES.
 */
@property (nonatomic) BOOL twoFingerPanTiltingEnabled;


/**
 * Enable one or more NMAMapView gestures.
 *
 * All gestures are enabled by default.
 * Pass NMAMapGestureTypeAll to enable all gestures.
 *
 * @param gestures A bit-mask combination of one or more NMAMapGestureType values.
 */
- (void)enableMapGestures:(NMAMapGestureType)gestures;

/**
 * Disables one or more NMAMapView gestures.
 *
 * Pass NMAMapGestureTypeAll to disable all gestures.
 * Disabling a gesture type will also disable that type for the NMAMapView's
 * gestureDelegate, but subviews of the map will still receive that gesture type.
 *
 * @param gestures A bit-mask combination of one or more NMAMapGestureType values.
 */
- (void)disableMapGestures:(NMAMapGestureType)gestures;

/**
 * Queries whether or not a gesture type is enabled on the `NMAMapView`.
 *
 * @param gesture The gesture type to query.
 */
- (BOOL)isMapGestureEnabled:(NMAMapGestureType)gesture;

 /**
 * Enables kinetic behaviour for one or more `NMAMapView` gestures.
 *
 * When kinetic behaviour is enabled, at the conclusion of a gesture (when the user's
 * finger is removed from the device), the map will continue moving in the direction
 * and with the speed of the original gesture before gradually coming to a stop.
 *
 * Pass NMAMapGestureTypeAll to enable kinetic behaciour for all gestures.
 *
 * @param gestures A bit-mask combination of one or more NMAMapGestureType values.
 *
 * @note Kinetc effect is visible for NMAMapGestureTypePan, NMAMapGestureTypePinch and NMAMapGestureTypeRotate gestures.
 */

- (void)enableKineticForGestures:(NMAMapGestureType)gestures;
/**
 * Disables kinetic behaviour for one or more NMAMapView gestures.
 *
 * Pass NMAMapGestureTypeAll to disable kinetic begaviour for all gestures.
 *
 * @param gestures A bit-mask combination of one or more NMAMapGestureType values.
 */
- (void)disableKineticForGestures:(NMAMapGestureType)gestures;

/**
 * Queries whether or not a gesture type is enabled on the `NMAMapView`.
 *
 * @param gesture The gesture type to query.
 */
- (BOOL)isKineticForGestureEnabled:(NMAMapGestureType)gesture;

#pragma mark Transformation

/**
 * The `NMAGeoCoordinates` of the world location corresponding to the
 * current screen position of the transformCenter.
 */
@property (nonatomic, nonnull) NMAGeoCoordinates *geoCenter;

/**
 * A measure of the apparent size of geographic features on the screen.
 *
 * The zoom level determines how "close" the map view is to the surface
 * of the Earth. Higher zoom levels give a closer view. An approximate
 * description of the appearance of various zoom levels is given below:
 *
 * - 0 - World level
 *
 * - 3 - Continent level
 *
 * - 5 - Country level
 *
 * - 10 - City level
 *
 * - 15 - Block level
 *
 * - 18 - Street level
 *
 * Zoom level values must be in the range [NMAMapViewMinimumZoomLevel,
 * NMAMapViewMaximumZoomLevel]; invalid values will be clamped to this
 * range. In addition to this fixed limit, the actual minimum zoom level
 * allowed for a map will depend on display parameters such as the size
 * of the map view and the PPI of the device.
 *
 * See also `NMAMapView::minimumZoomLevel`
 */
@property (nonatomic) float zoomLevel;

/**
 * Enables extended zoom levels. The max zoom level we currently support by default is 20.
 * With this feature enabled the max zoom level would be extended to 23. Disabled by default.
 *
 * IMPORTANT: this is a BETA feature, and is subject to change without notice.
 */
@property (nonatomic, getter = isExtendedZoomLevelsEnabled) BOOL extendedZoomLevelsEnabled;

/**
 * The current effective minimum zoom level of the map view.
 *
 * The effective minimum zoom level depends on the current display
 * parameters of the map and the device, and thus may change while
 * using the map. The value will never be lower than
 * NMAMapViewMinimumZoomLevel.
 */
@property (nonatomic, readonly) float minimumZoomLevel;

/**
 * The current effective maximum zoom level of the map view.
 *
 * The effective maximum zoom level depends on the current display
 * parameters of the map and the device, and thus may change while
 * using the map. The value will never be higher than
 * NMAMapViewMaximumZoomLevel.
 */
@property (nonatomic, readonly) float maximumZoomLevel;

/**
 * The orientation for the `NMAMapView`, in a range of degrees
 * between [0..360). Values outside this range will be clamped.
 *
 * By default, the map is oriented with north toward the top of the map
 * (zero degrees). As the orientation angle increases, the map rotates
 * counter-clockwise so that at 90 degrees, east is toward the top of the map.
 */
@property (nonatomic) float orientation;

/**
 * The desired tilt of the `NMAMapView` in degrees.
 *
 * The tilt controls the perspective at which the map is viewed. A value of
 * zero degrees corresponds to looking straight down at the map from above.
 * As the tilt value is increased, the view shifts to a 3D perspective.
 * The tilt must be in the range [0, NMAMapViewMaximumTilt]. Values outside
 * this range will be clamped.
 *
 * The tilt of the map may be further constrained at some zoom levels. For
 * example, no tilt is allowed at the lowest zoom levels when the globe is
 * visible. This is to provide a better user experience when interacting
 * with globe, since viewing a "tilted" globe does give any benefit.
 *
 * The value specified here is the desired tilt, but the actual tilt used to
 * render the map will be different if the desired tilt exceeds the lower or
 * upper zoom-dependent limit. The actual tilt is given by the clippedTilt
 * property.
 *
 * The minimum and maximum allowed tilts at a given zoom level can be
 * accessed using the minimumTiltAtZoomLevel: and maximumTiltAtZoomLevel:
 * methods, respectively.
 */
@property (nonatomic) float tilt;

/**
 * The actual tilt used to render the map, in degrees.
 *
 * See also `tilt`
 */
@property (nonatomic, readonly) float clippedTilt;

/**
 * The functional relationship between zoom and maximum tilt.
 *
 * Using the maximumTiltProfile, an application may control the maximum tilt
 * of a map at different zoom levels. The maximum applies to all sources of
 * map tilt, including gestures and animations.
 */
@property (nonatomic, strong, nonnull) NMATiltZoomProfile maximumTiltProfile;

/**
 * Returns the minimum allowed tilt at a given zoom level.
 */
- (float)minimumTiltAtZoomLevel:(float)zoomLevel;

/**
 * Returns the maximum allowed tilt at a given zoom level.
 */
- (float)maximumTiltAtZoomLevel:(float)zoomLevel;

#pragma mark Animation

/**
 * The point at which map movements and animations are centered.
 *
 * The transformCenter is a point within the bounds of the map that is
 * used to orient the map during transformations. For example, when one
 * of the setGeoCenter: methods is used, the specified geocoordinates will
 * be aligned with the transformCenter on the screen.
 *
 * The transformCenter is specified in relative coordinates in the range
 * {[0, 1], [0, 1]}, with {0, 0} representing the upper left corner of the
 * map and {1, 1} the lower right corner.
 * Values on or very near the edge of the map will be ignored.
 * Values above the horizon will be ignored.
 *
 * The default value is {0.5, 0.5}.
 *
 * @note The center point of map movements caused by gestures will depend
 * on the touch locations of the gestures and not on the transformCenter.
 */
@property (nonatomic) CGPoint transformCenter;

/**
 * The padding on the map.
 *
 * Allows you to specify custom padding, in points. Use this property to define invisible
 * area of the map around `NMAMapView`. Map functions such as `orientation`, `zoom` and
 * `center` will be adapted to the padding.
 *
 * The `padding` values should not be less than 0. Sum of left and right padding
 * should not be higher than map width. Sum of top and bottom padding should not
 * be higher than map height. Invalid padding values will be kept but not applied
 * until map size is sufficient for them.
 *
 * The default padding values are {0, 0, 0, 0}.
 *
 * @note Padding is based on `transformCenter`, so developer must not use both these
 * properties at the same time with `transformCenter` as the only one of them will be
 * taken into account, depending on the order of invocation.
 */
@property (nonatomic) UIEdgeInsets padding;

/**
 * Sets the geoCenter of the map with optional animation.
 *
 * @param geoCenter The NMAGeoCoordinates at which the map is centered.
 * @param animationType The animation method used to display the transformation.
 */
- (void)setGeoCenter:(nonnull NMAGeoCoordinates *)geoCenter
       withAnimation:(NMAMapAnimation)animationType
NS_SWIFT_NAME(set(geoCenter:animation:));

/**
 * Sets the orientation of the map with optional animation.
 *
 * @param orientation The orientation at which to set the map.
 * @param animationType The animation method used to display the transformation.
 */
- (void)setOrientation:(float)orientation
         withAnimation:(NMAMapAnimation)animationType
NS_SWIFT_NAME(set(orientation:animation:));

/**
 * Sets the zoomLevel of the map with optional animation.
 *
 * @param zoomLevel The zoomLevel at which to set the map.
 * @param animationType The animation method used to display the transformation.
 */
- (void)setZoomLevel:(float)zoomLevel
       withAnimation:(NMAMapAnimation)animationType
NS_SWIFT_NAME(set(zoomLevel:animation:));

/**
 * Sets the tilt of the map with optional animation.
 *
 * @param tilt The tilt at which to set the map.
 * @param animationType The animation method used to display the transformation.
 */
- (void)  setTilt:(float)tilt
    withAnimation:(NMAMapAnimation)animationType
NS_SWIFT_NAME(set(tilt:animation:));

/**
 * Simultaneously sets the geoCenter and zoomLevel of the map with optional
 * animation.
 *
 * Tilt and orientation are preserved.
 *
 * @param geoCenter The new geoCenter.
 * @param zoomLevel The new zoomLevel.
 * @param animationType The animation method used to display the transformation.
 */
- (void)setGeoCenter:(nonnull NMAGeoCoordinates *)geoCenter
           zoomLevel:(float)zoomLevel
       withAnimation:(NMAMapAnimation)animationType
NS_SWIFT_NAME(set(geoCenter:zoomLevel:animation:));

/**
 * Simultaneously sets one or more map transformation properties with optional
 * animation.
 *
 * Any combination of new properties may be passed to this method. To leave a property
 * unchanged, pass nil (geoCenter) or NMAMapViewPreserveValue (zoomLevel, orientation,
 * tilt) for that property.
 *
 * @param geoCenter The new geoCenter.
 * @param zoomLevel The new zoomLevel.
 * @param orientation The new orientation.
 * @param tilt The new tilt.
 * @param animationType The animation method used to display the transformation.
 */
- (void)setGeoCenter:(nullable NMAGeoCoordinates *)geoCenter
           zoomLevel:(float)zoomLevel
         orientation:(float)orientation
                tilt:(float)tilt
       withAnimation:(NMAMapAnimation)animationType
NS_SWIFT_NAME(set(geoCenter:zoomLevel:orientation:tilt:animation:));

/**
 * Positions the NMAMapView so that the specified world location coincides
 * with the specified screen location.
 *
 * The screen location must be within the bounds of the map view.
 *
 * @note Due to the curvature of the Earth, positioning may be inaccurate at
 * low zoom levels.
 *
 * @param coordinates The world location.
 * @param point The screen location.
 * @param animation The NMAMapAnimation type to use while moving the map.
 */
- (void)setGeoCoordinates:(nonnull NMAGeoCoordinates *)coordinates
                  toPoint:(CGPoint)point
            withAnimation:(NMAMapAnimation)animation
NS_SWIFT_NAME(set(geoCoordinates:to:animation:));

/**
 * Positions the NMAMapView so that the specified world location coincides
 * with the specified screen location.
 *
 * The screen point must be within the bounds of the map view.
 *
 * @note Due to the curvature of the Earth, positioning may be inaccurate at
 * low zoom levels.
 *
 * @param coordinates The world location.
 * @param point The screen location.
 * @param animation The NMAMapAnimation type to use while moving the map
 * @param zoomLevel Desired zoom level of the newly-centered `NMAMapView` (pass
 *              NMAMapViewPreserveValue to keep the current zoom level).
 * @param orientation Desired orientation of the newly-centered `NMAMapView` (pass
 *              NMAMapViewPreserveValue to keep the current orientation).
 * @param tilt Desired tilt angle of the newly-centered `NMAMapView` (pass
 *             NMAMapViewPreserveValue to keep the current tilt).
 */
- (void)setGeoCoordinates:(nonnull NMAGeoCoordinates *)coordinates
                  toPoint:(CGPoint)point
            withAnimation:(NMAMapAnimation)animation
                zoomLevel:(float)zoomLevel
              orientation:(float)orientation
                     tilt:(float)tilt
NS_SWIFT_NAME(set(geoCoordinates:to:animation:zoomLevel:orientation:tilt:));

/**
 * Sets the geo bounding box of the map view with optional animation.
 *
 * After this method completes, the full extents of the specified geo bounding
 * box will be visible in the map view. Depending on map orientation, this means
 * that the boundingBox property may return a different value than the one passed
 * to this method, because the map may be displaying some areas outside of the
 * input bounding box.
 *
 * @param boundingBox A `NMAGeoBoundingBox` to display after the transformation.
 * @param animationType A `NMAMapAnimation` to illustrate the transformation.
 */
- (void)setBoundingBox:(nonnull NMAGeoBoundingBox *)boundingBox
         withAnimation:(NMAMapAnimation)animationType
NS_SWIFT_NAME(set(boundingBox:animation:));

/**
 * Transforms the map to fit an arbitrary geo bounding box with the bounds
 * of a specific screen region with optional animation.
 *
 * Passing the bounds of the map view to this method is equivalent to calling
 * setBoundingBox:withAnimation:.
 *
 * @param boundingBox A `NMAGeoBoundingBox` to display after the transformation
 * @param screenRect The region of the view inside which the bounding box will be
 * located.
 * @param animationType The animation method used to perform the transformation.
 */
- (void)setBoundingBox:(nonnull NMAGeoBoundingBox *)boundingBox
            insideRect:(CGRect)screenRect
         withAnimation:(NMAMapAnimation)animationType
NS_SWIFT_NAME(set(boundingBox:inside:animation:));

#pragma mark Screen / World Conversion

/**
 * Converts a specified on-screen point to an equivalent `NMAGeoCoordinates`
 * object.
 *
 * @param point A point on the screen to convert.
 * @return The `NMAGeoCoordinates`, or nil if the conversion failed.
 */
- (nullable NMAGeoCoordinates *)geoCoordinatesFromPoint:(CGPoint)point
NS_SWIFT_NAME(geoCoordinates(from:));

/**
 * Converts a specified on-screen point to an equivalent `NMAGeoCoordinates`
 * object on a specific altitude.
 *
 * @param point A point on the screen to convert.
 * @param altitude A height in meters on which geo coordinates need to be calculated.
 * @return The `NMAGeoCoordinates`, or nil if the conversion failed.
 */
- (nullable NMAGeoCoordinates *)geoCoordinatesFromPoint:(CGPoint)point
                                  withAltitude:(float)altitude
NS_SWIFT_NAME(geoCoordinates(from:altitude:));

/**
 * Converts a specified `NMAGeoCoordinates` object to its equivalent
 * point in screen space.
 *
 * Valid geo coordinates will produce a valid point, even if the coordinates are
 * not on the screen or are above the visible horizon, as long as the coordinates
 * are not too far from the current map location. To check if coordinates are
 * within the bounds of the screen, use the CGRectContainsPoint method after making
 * the conversion.
 *
 * @param coordinates A `NMAGeoCoordinates` object to convert.
 * @return The on-screen `CGPoint`, or CGPoint.x = CGPoint.y = -CGFLOAT_MAX
 *         if the `NMAGeoCoordinates` object is nil.
 */
- (CGPoint)pointFromGeoCoordinates:(nonnull NMAGeoCoordinates *)coordinates
NS_SWIFT_NAME(point(from:));

/**
 * Calculates the point distance between two geo coordinates.
 *
 * @param startCoordinates Starting `NMAGeoCoordinates`.
 * @param endCoordinates Ending `NMAGeoCoordinates`.
 * @return The point distance between the `NMAGeoCoordinates`, or -CGFLOAT_MAX if
 * either of the coordinates parameters is nil or the calculation cannot be performed.
 *
 * @note The calculation will fail if the coordinates are too far apart or too
 * far from the current location of the map.
 */
- (double)pointDistanceFromGeoCoordinates:(nonnull NMAGeoCoordinates *)startCoordinates
                         toGeoCoordinates:(nonnull NMAGeoCoordinates *)endCoordinates
NS_SWIFT_NAME(pointDistance(from:to:));

/**
 * Get the screen-space to world-space conversion factor at a specified zoom level.
 *
 * @param zoomLevel The zoom level at which to retrieve the conversion factor.
 * @return The conversion factor in meters per point.
 *
 * @note The conversion factor is based on a straight-line distance between two points;
 * that is, it does not take into account the curvature of the Earth.
 */
- (float)metersPerPointAtZoomLevel:(float)zoomLevel;

#pragma mark Snapshots

/**
 * Creates a temporary map view with a specified size and position and then
 * renders it to a UIImage - nothing is rendered to the screen.
 *
 * This class method is used to create a static image of a map. The snapshot will have
 * the same visual appearance as an equivalent NMAMapView with the same geocenter, zoom,
 * orientation and frame size.
 *
 * Only one snapshot will be processed at a time, but any number may be queued up via
 * successive calls to this method. Snapshots will be processed in the order they are
 * received.
 *
 * Unlike snapshotWithBlock:, this method will never take a snapshot whilst the app is
 * backgrounded. If the app is in the background then the snapshot will be deferred until
 * the application enters the foreground again.
 *
 * @note If not already downloaded, this method will download the required map data for
 * the region specified, so a snapshot will take longer to complete for a region where
 * no map data has been downloaded.
 */
+ (void)snapshotWithGeoCoordinates:(nonnull NMAGeoCoordinates *)coordinates
                         zoomLevel:(float)zoom
                       orientation:(float)orientation
                              size:(CGSize)size
                             block:(void (^ _Nonnull)(UIImage * _Nonnull snapshot))resultBlock
NS_SWIFT_NAME(snapshot(geoCoordinates:zoomLevel:orientation:size:_:));

/**
 * Creates a UIImage of the NMAMapView's current appearance. The map view
 * will redraw itself before capturing the image.
 *
 * Only one snapshot may be requested at a time. If multiple requests are made
 * together, only one snapshot will be produced and only the block passed with
 * the last call to this method will be invoked.
 *
 * This method is asynchronous. The snapshot will only be generated after the
 * map has been re-rendered; thus, if the visual state of the map is changed
 * immediately after calling this method (and before the block has executed),
 * the generated snapshot will reflect the changes made to the map.
 *
 * The snapshot will exactly match the appearance of the actual map view itself.
 * If the map is moved to a location where data is not yet available and a
 * snapshot is requested, the snapshot will reflect the lack of map data. To
 * ensure a useful snapshot in this case, the mapViewDidDraw: method of the
 * `NMAMapViewDelegate` protocol can be used to trigger the snapshot after map
 * data has been downloaded and rendered. Be aware that triggering a snapshot
 * causes another redraw, so be sure to add protection to avoid continuously
 * requesting snapshots in mapViewDidDraw:
 *
 * Snapshots can not be taken whilst the app is backgrounded. If the app is in the
 * background and software rendering is active then a nil UIImage will be passed
 * to the result block on the next software rendered frame. If software rendering is not
 * active then the snapshot will be deferred until the application enters the foreground
 * again. See the softwareRenderToBitmap property for details of when software
 * rendering is active and how to get software rendered bitmaps in the background.
 *
 * @note UIView objects visible within the frame of the map (such as subviews) will
 * NOT be captured in the snapshot. NMAMapOverlay objects will NOT be captured unless
 * their displayedAsMarker property is set to YES.
 */
- (void)snapshotWithBlock:(void (^ _Nonnull)(UIImage * _Nullable snapshot))resultBlock;

#pragma mark Map Objects

/**
 * Adds a `NMAMapObject` to the `NMAMapView`.
 *
 * The object is added to `NMAMapLayerTypeForeground` layer.
 *
 * @param object A `NMAMapObject` to add.
 * @return YES if the map object was added successfully, NO otherwise (if the
 * object has already been added, as duplicates are not allowed).
 *
 */
- (BOOL)addMapObject:(nonnull NMAMapObject *)object
NS_SWIFT_NAME(add(mapObject:));

/**
 * Adds a `NMAMapObject` to the `NMAMapView`.
 *
 * The object is added to the specified `NMAMapLayerType`.
 *
 * @param object A `NMAMapObject` to add.
 *
 * @param layer A `NMAMapLayerType` layer to add the object to.
 *
 * @return YES if the map object was added successfully, NO otherwise (if the
 * object has already been added, as duplicates are not allowed).
 */
- (BOOL)addMapObject:(nonnull NMAMapObject *)object toLayer:(NMAMapLayerType)layer
NS_SWIFT_NAME(add(mapObject:to:));

/**
 * Adds a `NSArray` of `NMAMapObject` objects to the `NMAMapView`.
 *
 * @param objects A `NSArray` of `NMAMapObject` objects to add
 * @return YES if all map objects were added successfully, NO otherwise.
 */
- (BOOL)addMapObjects:(nonnull NSArray<NMAMapObject *> *)objects
NS_SWIFT_NAME(add(mapObjects:));

/**
 * Adds a `NSArray` of `NMAMapObject` objects to the `NMAMapView`.
 *
 * @param objects A `NSArray` of `NMAMapObject` objects to add.
 * @param layer A `NMAMapLayerType` layer to add the object to.
 * @return YES if all map objects were added successfully, NO otherwise.
 */
- (BOOL)addMapObjects:(nonnull NSArray<NMAMapObject *> *)objects toLayer:(NMAMapLayerType)layer
NS_SWIFT_NAME(add(mapObjects:to:));

/**
 * Obtains all `NMAMapObject` objects added to the `NMAMapView` by user.
 *
 * @note Objects will be returned in an arbitrary order.
 * @return The `NSArray` of all `NMAMapObject` objects.
 */
- (nonnull NSArray<NMAMapObject *> *)allMapObjects;

/**
 * Removes an existing `NMAMapObject` from the `NMAMapView`.
 *
 * @param object A `NMAMapObject` to remove.
 * @return YES if the map object was removed successfully, NO otherwise.
 */
- (BOOL)removeMapObject:(nonnull NMAMapObject *)object
NS_SWIFT_NAME(remove(mapObject:));

/**
 * Removes a `NSArray` of `NMAMapObject` objects from the `NMAMapView`.
 *
 * @param objects A `NSArray` of `NMAMapObject` objects to remove.
 * @return YES if all map objects were removed successfully, NO otherwise.
 */
- (BOOL)removeMapObjects:(nonnull NSArray<NMAMapObject *> *)objects
NS_SWIFT_NAME(remove(mapObjects:));

/**
 * Removes all `NMAMapObject` objects added to the `NMAMapView` by user.
 * @return YES, if all `NMAMapObject` objects were removed successfully, NO otherwise.
 */
- (BOOL)removeAllMapObjects;

/**
 * Returns a `NSArray` of all `NMAViewObject` objects that are selected at
 * a specified point on the screen.
 *
 * @param point An on-screen `CGPoint` specified in logical coordinates.
 * @return The `NSArray` of selected `NMAViewObject` objects.
 *
 * @note Use isKindOfClass: to further determine NMAViewObject type instead of
 * isMemberOfClass:.
 */
- (nonnull NSArray<NMAViewObject *> *)objectsAtPoint:(CGPoint)point;

/**
 * Returns a `NSArray` of all visible `NMAViewObject` objects that are
 * selected at a specified point on the screen.
 *
 * @param point An on-screen `CGPoint` specified in logical coordinates.
 * @return The `NSArray` of selected `NMAViewObject` objects.
 *
 * @note Use isKindOfClass: to further determine NMAViewObject type instead of
 * isMemberOfClass:.
 */
- (nonnull NSArray<NMAViewObject *> *)visibleObjectsAtPoint:(CGPoint)point;

/**
 * Attaches cluster layer to the map. From this moment on the markers added to the layer will be
 * also added to the map. After the layer is added clustering will happen automatically.
 *
 * @param clusterLayer Layer to add.
 * @return YES if successfully added.
 */
- (BOOL)addClusterLayer:(nonnull NMAClusterLayer *)clusterLayer
NS_SWIFT_NAME(add(clusterLayer:));

/**
 * Detaches the cluster from the map. After this call completes markers on this layer will be
 * removed from the map.
 *
 * @param clusterLayer Layer to remove.
 * @return YES if successfully removed.
 */
- (BOOL)removeClusterLayer:(nonnull NMAClusterLayer *)clusterLayer
NS_SWIFT_NAME(remove(clusterLayer:));

#pragma mark Map Overlays

/**
 * Adds a `NMAMapOverlay` object to the `NMAMapView`.
 *
 * @param overlay A `NMAMapOverlay` object to add.
 * @return YES if the map overlay was added successfully, NO otherwise.
 */
- (BOOL)addMapOverlay:(nonnull NMAMapOverlay *)overlay
NS_SWIFT_NAME(add(mapOverlay:));

/**
 * Removes an existing `NMAMapOverlay` object from the `NMAMapView`.
 *
 * @param overlay A `NMAMapOverlay` object to remove.
 * @return YES if the map overlay was removed successfully, NO otherwise.
 */
- (BOOL)removeMapOverlay:(nonnull NMAMapOverlay *)overlay
NS_SWIFT_NAME(remove(mapOverlay:));

#pragma mark Copyright

/**
 * The copyright for the `NMAMapView`.
 */
@property (nonatomic, readonly, nonnull) NSString *copyright;

/**
 * The copyright logo position for the `NMAMapView`.
 *
 * @note Logo is not shown when its size is greater than 1/8 of NMAMapView's height or width.
 * @note Valid values are NMALayoutPositionTopLeft, NMALayoutPositionTopCenter,
 * NMALayoutPositionTopRight, NMALayoutPositionBottomLeft, NMALayoutPositionBottomCenter,
 * and NMALayoutPositionBottomRight.
 */
@property (nonatomic) NMALayoutPosition copyrightLogoPosition;

/**
 * The distance in points that the copyright logo will be from the top or
 *  bottom edge of the NMAMapView.
 *
 * Values less than 10.0 will be ignored.
 */
@property (nonatomic) float copyrightLogoVerticalMargin;

/**
 * The distance in points that the copyright logo will be from the left or
 *  right edge of the NMAMapView.
 *
 * Values less than 10.0 will be ignored.
 *
 * @note Does not apply when the copyrightLogoPosition is NMALayoutPositionTopCenter
 * or NMALayoutPositionBottomCenter.
 */
@property (nonatomic) float copyrightLogoHorizontalMargin;


#pragma mark - Transit

/**
 * The transit stop display mode for the `NMAMapView`.
 */
@property (nonatomic) NMAMapTransitDisplayMode transitDisplayMode;

/**
 * The map transit layer for the `NMAMapView`.
 */
@property (nonatomic, readonly, nonnull) NMAMapTransitLayer *mapTransitLayer;


#pragma mark - Traffic

/**
 * Indicates traffic visibility for the `NMAMapView`.
 *
 * This provides global control over traffic visibility on the map. To change
 * the visibility of an individual `NMATrafficLayer` please see showTrafficLayers,
 * hideTrafficLayers.
 *
 * Traffic can only be displayed on one map at a time. It is recommended that you turn off
 * traffic display on other maps before enabling traffic display on a new map otherwise the
 * results may be unpredictable. If multiple maps are shown at the same time with
 * trafficVisible YES, only one will display traffic.
 *
 * The traffic is not visible if access to this operation is denied. Contact
 * your HERE representative for more information.
 */
@property (nonatomic, getter = isTrafficVisible) BOOL trafficVisible;

/**
 * Displays one or more traffic layers.
 *
 * The layers to be displayed are specified using the NMATrafficLayer.
 * Traffic layers which are already visible will not be affected.
 *
 * @param layers An "OR" combination of layers to be displayed.
 *
 * @note No traffic layers will be shown unless trafficVisible is YES. However,
 * changes to individual NMATrafficLayer visibility settings will be saved even if
 * trafficVisible is currently NO. They will be applied when trafficVisible is YES.
 */
- (void)showTrafficLayers:(NMATrafficLayer)layers
NS_SWIFT_NAME(show(trafficLayers:));

/**
 * Hides one or more traffic layers.
 *
 * The layers to be hidden are specified using the NMATrafficLayer.
 * Traffic layers which are already hidden will not be affected.
 *
 * @param layers An "OR" combination of layers to be hidden.
 *
 * @note No traffic layers will be shown unless trafficVisible is YES. However,
 * changes to individual NMATrafficLayer visibility settings will be saved even if
 * trafficVisible is currently NO. They will be applied when trafficVisible is YES.
 */
- (void)hideTrafficLayers:(NMATrafficLayer)layers
NS_SWIFT_NAME(hide(trafficLayers:));

/**
 * Queries whether a given traffic layer is displayed.
 *
 * By default all traffic layers are visible.
 *
 * @param layer The traffic layer type to check.
 *
 * @note No traffic layers will be shown unless trafficVisible is YES. However,
 * the state of individual NMATrafficLayer visibility settings will still be saved
 * when trafficVisible is NO. Therefore, this function may return YES even when
 * trafficVisible is NO. The visibility settings will be applied when trafficVisible
 * is YES.
 */
- (BOOL)isTrafficLayerVisible:(NMATrafficLayer)layer;

/**
 * Sets the minimal severity of traffic flows and events to display.
 *
 * For example, specifying NMATrafficSeverityBlocking means that only blocking events
 * will be displayed and NMATrafficSeverityNormal means that all events
 * (NMATrafficSeverityNormal, NMATrafficSeverityHigh, NMATrafficSeverityVeryHigh,
 * NMATrafficSeverityBlocking) will be displayed.
 *
 * Traffic flow lines are color coded as follows:
 * NMATrafficSeverityNormal - Green
 * NMATrafficSeverityHigh - Amber
 * NMATrafficSeverityVeryHigh - Red
 * NMATrafficSeverityBlocking - Black.
 *
 * Defaults to NMATrafficSeverityNormal.
 *
 * @note Attempts to set NMATrafficSeverityUndefined will be ignored.
 */
@property (nonatomic) NMATrafficSeverity trafficDisplayFilter;

#pragma mark - Road Information

/**
 * Get the road elements for a geo bounding area.
 *
 * @param geoArea A `NMAGeoBoundingBox` to get the road elements
 * @return NSArray of NMARoadElement of the geo area.
 */
- (nonnull NSArray<NMARoadElement *> *)roadElementsInArea:(nonnull NMAGeoBoundingBox *)geoArea;

/**
 * Get the road elements for a geo bounding area.
 *
 * @param geoArea A `NMAGeoBoundingBox` to get the road elements
 * @param marcLangCode A international MARC code for the language of the road element text
 * @return NSArray of NMARoadElement of the geo area.
 */
- (nonnull NSArray<NMARoadElement *> *)roadElementsInArea:(nonnull NMAGeoBoundingBox *)geoArea
                                                     lang:(nullable NSString *)marcLangCode;

/**
 * Get the road element for a geo coordinates. This method returns nil if the coordinates is invalid
 * or there is no `NMARoadElement` close enough to the given coordinates.
 *
 * @param coordinates A `NMAGeoCoordinates` that defines the coordinate to retrieve `NMARoadElement`
 * @return `NMARoadElement` of the geo coordinate.
 */
- (nullable NMARoadElement *)roadElementAtCoordinates:(nonnull NMAGeoCoordinates *)coordinates;

/**
 * Get the road element for a geo coordinates. This method returns nil if the coordinates is invalid
 * or there is no `NMARoadElement` close enough to the given coordinates.
 *
 * @param coordinates A `NMAGeoCoordinates` that defines the coordinate to retrieve `NMARoadElement`
 * @param marcLangCode A international MARC code for the language of the road element text
 * @return `NMARoadElement` of the geo coordinate.
 */
- (nullable NMARoadElement *)roadElementAtCoordinates:(nonnull NMAGeoCoordinates *)coordinates
                                                 lang:(nullable NSString *)marcLangCode;

#pragma mark - Custom Raster Tiles

/**
 * Adds a NMAMapTileLayer to the map view for rendering custom raster tiles.
 *
 * @param tileLayer NMAMapTileLayer instance to be added to the map view. Ignores
 *                  attempts to add the same NMAMapTileLayer instance twice.
 *
 * @note Attempting to add a single NMAMapTileLayer instance to multiple NMAMapView
 * instances is not supported and will result in undefined behavior.
 */
- (void)addMapTileLayer:(nonnull NMAMapTileLayer *)tileLayer
NS_SWIFT_NAME(add(mapTileLayer:));

/**
 * Removes a NMAMapTileLayer from the map view.
 *
 * @param tileLayer NMAMapTileLayer instance to be removed from the map view. Does nothing
 *                  if tileLayer has not been added to the map view yet.
 */
- (void)removeMapTileLayer:(nonnull NMAMapTileLayer *)tileLayer
NS_SWIFT_NAME(remove(mapTileLayer:));

/**
 * Returns an array of NMAMapTileLayer instances that have been added to the
 * map view.
 *
 * @return NSArray of NMAMapTileLayer instances.
 */
- (nonnull NSArray<NMAMapTileLayer *> *)mapTileLayers;

#pragma mark - Software Rendering

/**
 * Controls whether the software renderer renders to a bitmap.
 *
 * Software rendering is only active when the application is backgrounded and navigation map
 * tracking is enabled (see [NMANavigationManager backgroundMapTrackingMaximumRefreshRate]).
 *
 * If this property is set to YES, and if software rendering is currently active, then the
 * rendered bitmap will be available via the NMAMapViewDelegate
 * mapView:didRenderBitmap:withWidth:height:bytesPerPixel: callback.
 *
 * Defaults to NO.
 *
 * IMPORTANT: Software Rendering is a Beta feature, and associated methods and behaviours
 * are subject to change without notice. Software rendering has the following limitations:
 * 1) Does not work with NMAProjectionTypeGlobe. The map will automatically switch to use
 *    NMAProjectionTypeMercator whenever software rendering is active.
 * 2) Does not render 3D models. This includes extruded buildings and the default
 *    NMAPositionIndicator. You may configure NMAPositionIndicator to use an image via:
 *        map.positionIndicator.displayObject = [NMAMapMarker mapMarkerWithGeoCoordinates:
 *            [NMAGeoCoordinates new] image:[UIImage imageNamed:@"my_image"]];
 * 3) Is CPU intensive which can cause your app to be killed when running in the background.
 *    See [NMANavigationManager backgroundMapTrackingMaximumRefreshRate] for details on how
 *    to avoid this.
 */
@property (nonatomic) BOOL softwareRenderToBitmap;

@end
